[env]
    monitor_speed = 115200

[env:blackpill_f411ce]
    platform = ststm32
    board = blackpill_f411ce
    framework = arduino
    upload_protocol = stlink
    build_src_filter = +<mainSTM32.cpp> +<BMP/> +<MPU/> +<PID/> +<KALMAN/> +<ESC/> +<COMM_STM/> +<VL53L0/> +<ina219/> +<gps_neo6m/> +<Hmc5883l/> -<mainESP32.cpp> -<INTERNET/> -<teste/> -<output/>
    build_flags =
        -DUSAR_INA219=1
        -I src/BMP
        -I src/MPU
        -I src/PID
        -I src/KALMAN
        -I src/ESC
        -I src/COMM_STM
        -I src/VL53L0
        -I src/ina219
        -I src/gps_neo6m
        -I src/Hmc5883l
        -Wall
        -Wextra

    lib_deps =
        https://github.com/Every-Flavor-Robotics/Adafruit_AHRS.git
        https://github.com/r-downing/AutoPID.git
        stm32duino/STM32duino VL53L0X@2.0.1
        adafruit/Adafruit INA219@^1.2.3
        mikalhart/TinyGPSPlus@^1.0.3
        adafruit/Adafruit HMC5883 Unified@^1.2.0
        
[env:blackpill_f411ce_debug]
extends = env:blackpill_f411ce
build_flags = ${env:blackpill_f411ce.build_flags} -DSTM32_DEBUG_UART=1

[env:esp32doit-devkit-v1]
    platform = espressif32
    board = esp32doit-devkit-v1
    framework = arduino
    upload_speed = 115200
    lib_compat_mode = strict
    build_src_filter = +<mainESP32.cpp> +<INTERNET/> +<COMM_ESP/> -<mainSTM32.cpp> -<BMP/> -<MPU/> -<PID/> -<KALMAN/> -<ESC/> -<teste/> -<output/>
    build_flags =
        -I src/INTERNET
        -I src/COMM_ESP
        -Wall
        -Wextra
    lib_deps =
        https://github.com/Every-Flavor-Robotics/Adafruit_AHRS.git
        https://github.com/r-downing/AutoPID.git
